### ISSUE TITLE
Logical error in Purse.withdraw(Valuable)

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/coinpurse-pknn1#13]
Are you sure that all numbers which less than 1 are negative?

https://github.com/OOP2018/coinpurse-pknn1/blob/70506f730cfb46d1495f5fcee99fdaece24bdf0e/src/coinpurse/Purse.java#L96-L99

**Comment by chinnonae** [comment]
Why does withdraw amount less than 1 is not allowed? What if I wanted to withdraw 0.1 BTC or 50-satang?

https://github.com/OOP2018/coinpurse-pknn1/blob/c892f06452b4b0769106919dbe06088f63662903/src/coinpurse/Purse.java#L96-L99

**Comment by ghost** [comment]
I fixed this issue, please edit the score.
