### ISSUE TITLE
Incorrect compareTo

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-pknn1#6]
`int compareTo(Coin coin) o`
```
order Coins by value so that the coin with smaller
value comes first. The meaning of compareTo is:
a.compareTo(b) < 0 if a has order before b
               > 0 if a has order after b
               = 0 if a and b have same order
For now, compareTo ignores the currency value.
```
https://github.com/OOP2018/coinpurse-pknn1/blob/ff07644b1b43784885c07aa759e68554f1acb502/src/coinpurse/Coin.java#L62-L68

**Comment by ghost** [comment]
พี่แจ๊คเป็นคนบอกให้สลับค่ามันเองอ้ะะะะะะ!!!!!!!!!!!!!!!!!!!!!!!

**Comment by kykungz** [comment]
พี่ขอโต้ด
พอรันกับ unit test ที่จิมส่งมาให้ใหม่ มันมีตรวจ `compareTo` ด้วยอะ
แก้ `compareTo` ละไปเพิ่ม `Collections.reverse(money)` ใน `withdraw` แทนละกัน

**Comment by kykungz** [comment]
อ่อแก้แล้ว ท่ดๆ
